.gitignore
testrecords01/main.go

Issue 3.dockter.1

---

truthset/customers.go
truthset/main.go
truthset/reference.go
truthset/watchlist.go

#3 Define Record type

---

go.mod
go.sum
record/doc.go
record/go.mod
record/main.go
record/record.go
record/record_test.go

Issue 7.ron.0

---

CHANGELOG.md

#7 updated change log for release

---

observed/main.go
observer/main.go

#13 add Observer pattern interfaces

---

README.md
g2engineconfigurationjson/doc.go
g2engineconfigurationjson/g2engineconfigurationjson.go
g2engineconfigurationjson/g2engineconfigurationjson_test.go
g2engineconfigurationjson/main.go

#15 Migrate g2engineconfigurationjson

---

README.md
record/record_test.go

#17 Fix spelling

---

.github/workflows/make-go-tag.yaml

#20 Add make-go-tag.yaml

---

CHANGELOG.md
Makefile
engineconfigurationjsonparser/engineconfigurationjsonparser.go
engineconfigurationjsonparser/engineconfigurationjsonparser_test.go
engineconfigurationjsonparser/main.go
go.mod

Issue 27.dockter.1

---

.github/workflows/add-dependabot-request-to-project-t-comm.yaml
.github/workflows/add-issue-to-project-t-comm.yaml
.github/workflows/go-test.yaml
CHANGELOG.md
README.md
docs/development.md
docs/errors.md
docs/examples.md
go.mod
go.sum

Issue 33.dockter.1

---

.github/workflows/go-security.yaml
CHANGELOG.md
go.mod
go.sum

#33 Prepare for versioned release

---

.github/workflows/dependabot-automation.yaml

#38 update token prefix

---

CHANGELOG.md
g2engineconfigurationjson/g2engineconfigurationjson.go
g2engineconfigurationjson/g2engineconfigurationjson_darwin.go
g2engineconfigurationjson/g2engineconfigurationjson_linux.go
g2engineconfigurationjson/g2engineconfigurationjson_linux_test.go
g2engineconfigurationjson/g2engineconfigurationjson_windows.go
g2engineconfigurationjson/g2engineconfigurationjson_windows_test.go
go.mod
go.sum
main.go

Issue 45.dockter.2

---

.gitignore
Makefile
Makefile.darwin
Makefile.osdetect
g2engineconfigurationjson/g2engineconfigurationjson_darwin.go

Fixes issue #57 and adds OS Detection and `SENZING_TOOLS_SENZING_DIRECTORY` setting for Makefile.

Makefile OS switching and fix for g2engineconfigurationjson_darwin.go

---

g2engineconfigurationjson/g2engineconfigurationjson.go

#54 Add check for RESOURCEPATH/templates/g2config.json

---

CHANGELOG.md
jsonutil/jsonutil.go
jsonutil/jsonutil_test.go

Resolves #71 
- Added `jsonutil.Flatten()` function to coalesce a string and error tuple into a string
- Added test cases and examples for new flatten function

Version 0.2.9: Adds Flatten() function

---

.github/workflows/go-test-linux.yaml

#73 Minor update

---

CHANGELOG.md
fileutil/doc.go
fileutil/fileutil.go
fileutil/fileutil_test.go
fileutil/main.go
jsonutil/jsonutil_test.go

Resolves #82 
- Added `fileutil` package with `fileutil.CopyFile()` function
- Added tests and examples for `fileutil.CopyFile()` function

Version 0.2.13 with fileutil package containing fileutil.CopyFile(src, dest, overwrite) function

---

.github/workflows/go-test-darwin.yaml
.github/workflows/go-test-linux.yaml
.github/workflows/go-test-windows.yaml
g2engineconfigurationjson/g2engineconfigurationjson_darwin_test.go
g2engineconfigurationjson/g2engineconfigurationjson_windows.go
g2engineconfigurationjson/g2engineconfigurationjson_windows_test.go
go.mod
go.sum

86.dockter.1

---

.gitignore
CHANGELOG.md
go.sum

#86 Prepare for versioned release

---

CHANGELOG.md
Makefile
g2engineconfigurationjson/g2engineconfigurationjson.go
g2engineconfigurationjson/g2engineconfigurationjson_darwin.go
g2engineconfigurationjson/g2engineconfigurationjson_darwin_test.go
g2engineconfigurationjson/g2engineconfigurationjson_examples_test.go
g2engineconfigurationjson/g2engineconfigurationjson_linux_test.go
g2engineconfigurationjson/g2engineconfigurationjson_test.go
g2engineconfigurationjson/g2engineconfigurationjson_windows.go
g2engineconfigurationjson/g2engineconfigurationjson_windows_test.go

91.dockter.1

---

.github/workflows/add-dependabot-request-to-project-t-comm.yaml
.github/workflows/add-issue-to-project-t-comm.yaml
.github/workflows/add-triage-label.yaml
.github/workflows/go-test-darwin.yaml
.github/workflows/go-test-linux.yaml
.github/workflows/go-test-windows.yaml
.github/workflows/gosec.yaml
.github/workflows/identify-customer.yaml
CHANGELOG.md
Makefile
Makefile.darwin
Makefile.linux
Makefile.windows

#94 Refactor to template

---

.github/workflows/go-test-windows.yaml

#116 Try staging-v4 for Windows

---

go.mod
go.sum

#33 Update dependencies

---

.github/linters/.golangci.yaml
.github/workflows/go-test-darwin.yaml
.github/workflows/go-test-windows.yaml
CHANGELOG.md
README.md
go.mod
go.sum
makefiles/darwin.mk
makefiles/linux.mk
settings/settings.go
settings/settings_darwin.go
settings/settings_examples_test.go
settings/settings_linux.go
settings/settings_test.go
settings/settings_windows.go
settingsparser/settingsparser_basic.go

#131 Change DatabaseUrl to DatabaseURL

---

.github/workflows/go-test-windows.yaml
CHANGELOG.md
fileutil/fileutil_examples_test.go
fileutil/fileutil_test.go
settings/settings.go

#133 Remove unicode from JSON

---

.github/workflows/go-test-darwin.yaml
.github/workflows/go-test-linux.yaml
.github/workflows/go-test-windows.yaml

update osx and win install

---

CHANGELOG.md
go.mod
go.sum
jsonutil/jsonutil.go
jsonutil/jsonutil_examples_test.go
jsonutil/jsonutil_test.go

#140 Add jsonutil.PrettyPrint

---

.github/workflows/go-test-darwin.yaml
CHANGELOG.md
bin/macos_exec_dyld.sh
go.mod
go.sum
settings/settings.go
settings/settings_darwin.go
settings/settings_windows.go

#144 Update dependencies

---

CHANGELOG.md
debug/debug_basic.go
debug/debug_test.go
debug/main.go
go.mod
go.sum
jsonutil/jsonutil.go
jsonutil/jsonutil_examples_test.go
jsonutil/jsonutil_test.go
settings/settings.go
settings/settings_darwin_test.go
settings/settings_examples_test.go
settings/settings_linux_test.go
settings/settings_test.go
settings/settings_windows_test.go
settingsparser/main.go
settingsparser/settingsparser_basic.go
settingsparser/settingsparser_examples_test.go
settingsparser/settingsparser_test.go

#143 Update database URIs

---

.github/linters/.golangci.yaml
.github/linters/bearer.yml
.github/workflows/bearer.yaml
.github/workflows/go-proxy-pull.yaml
.github/workflows/go-test-linux.yaml
.github/workflows/go-test-windows.yaml
.vscode/cspell.json
CHANGELOG.md
Makefile
bearer.ignore
fileutil/fileutil.go
fileutil/fileutil_test.go
go.mod
go.sum
jsonutil/jsonutil.go
jsonutil/jsonutil_examples_test.go
jsonutil/jsonutil_test.go
makefiles/linux.mk
record/record.go
settings/settings.go
settingsparser/settingsparser_basic.go
tls/tls.go
tls/tls_linux.go
wraperror/wraperror.go
wraperror/wraperror_examples_test.go
wraperror/wraperror_test.go

#159 Change wraperror.Errorf signature

---

.github/workflows/go-test-darwin.yaml
.github/workflows/go-test-linux.yaml
.github/workflows/go-test-windows.yaml

#163 nightly cron job for install testing

---

CHANGELOG.md
go.mod
go.sum
jsonutil/jsonutil.go
jsonutil/jsonutil_examples_test.go
jsonutil/jsonutil_test.go
wraperror/wraperror.go
wraperror/wraperror_test.go

#162 Improve error wrapping

---

.github/workflows/go-test-darwin.yaml
.github/workflows/go-test-linux.yaml
.github/workflows/go-test-windows.yaml

#170 4.0 updates, switch from beta to staging, test prod
